# Site settings
title: Gamers Connect UH
description: Connecting gamers at the University of Hawai ªi. Find teammates, sessions, and local events.

remote_theme: pages-themes/cayman

url: "https://gamers-connect.github.io" # NO trailing slash
baseurl: ""
